export const DATA_FETCHING = "DATA_FETCHING";
export const DATA_FETCHING_SUCCESS ="DATA_FETCHING_SUCCESS";
export const DATA_FETCHING_FAIL = "DATA_FETCHING_FAIL";


export const LOAD_MORE_SUCCESS = "LOAD_MORE_SUCCESS ";
export const LOAD_RESET = "LOAD_RESET";